### ISSUE TITLE
Software to implement microsimulation

### ISSUE THREAD

**Issue by Robinlovelace** [CatchDat/humanleague#2]
This involves generalising #1 so synthetic populations can be generated for other cities.

**Comment by virgesmith** [comment]
The idea was to come up with a novel approach that generates only integer populations, unlike existing methods (e.g. IPF, ML, chi squared, least squares) where populations are generally fractional.  
Original approach was to use quasirandom sampling and subsequently make any minor adjustments to fit the marginals. It's transpired there are cases where this approach never seems to be able to generate a valid population. 
After a rethink, I decided to use sampling without replacement using an underlying quasirandom generator. This is guaranteed to work every time but may result in statistically unlikely populations. In order to give some measure of the degeneracy of the resulting population I've added chi-square and p-value statistics. End-user can then resample depending on their p-value threshhold. 

This is essentially a working Rcpp package now. It may need some further tweaks but next steps are to write it up and publish it on CRAN.
